[package]
name = "r-dpool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"  # 使用最新的稳定版本
num_cpus = "1.13"  # 使用最新的稳定版本
once_cell = "1.10.0"
